### PR TITLE
add new interface for init configuration

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by songgao** [comment]
@lixin9311 This should be helpful for setting `ComponentID` and other stuff in Windows without affecting other platforms. Let me know if it look good. Thanks!

**Comment by lixin9311** [comment]
Yes, I think IFF_NO_PI could be an optional flag in the config. And so is the IP address and Mask when opening TUN on Windows. You can use the names, LocalIP, RemoteNetwork, RemoteNetmask.

**Comment by songgao** [comment]
Good point on `IFF_NO_PI`! I'll do it in a separate PR.

I'll merge this into master then. Would you mind rebasing your branch against master, and adding those fields you suggested in `PlatformSpecificParams` in your branch? Thanks!

**Comment by lixin9311** [comment]
And you may use net.IP for LocalIP, and net.IPNet(it contains both Network address and Mask) for RemoteNet in platform config for Windows

**Pull request merged**
