### PR TITLE
Added support for Linux ARM Android version adding file checking of T…

### PR DESCRIPTION
**Pull request by dgrr**
…UN device in /dev/tun instead of /dev/net/tun

### CODE REVIEW

**Comment by songgao** [comment]
Thanks for the PR; is the location `/dev/tun` documented somewhere? Also it seems it's best to make it opt-in through [`PlatformSpecificParams `](https://github.com/songgao/water/blob/dc106b419556b93288adff21fe0c86e8c9b10f9b/params_linux.go#L20) since in most platforms it's the standard `/dev/net/tun`. Perhaps add a field `DeviceFilePath` to it (on Linux only), and check that in `newTun` and `newTap`?

**Comment by themester** [comment]
Um, okay, I am going to set as parameter in https://github.com/songgao/water/blob/dc106b419556b93288adff21fe0c86e8c9b10f9b/params_linux.go#L20 and make another commit.

**Comment by songgao** [comment]
Cool thanks! Also on a second thought I think `OverrideDeviceFilePath` might be a better name; up to you!

**Comment by FlowerWrong** [comment]
`/dev/tun` and `/dev/net/tun` can be setuped as const.

```go
const (
	DevNetTun = "/dev/net/tun"
	DevTun    = "/dev/tun"
)
```

**Pull request closed without merging**
